name: check-all-parts
on: [push, pull_request]
jobs:
  python-scripts:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install requirements
        run: pip install -r scripts/requirements.txt
      - name: Avoid non acsii in part and svg filenames
        run: python scripts/checkascii.py .
      - name: Check that image filenames use same case
        run: python scripts/checkcase.py
      - name: Look for suspicious connector numbering
        run: python scripts/connectors_misnumbered.py -d .
      - name: Avoid duplicate files
        run: python scripts/checkcopies.py -d svg
      - name: Dry run script to test the script itself
        run: python scripts/obsolete.py core/sparkfun-connectors-rca-.fzp dummy -s
      - name: Check that SVGs have proper layer ids
        run: python scripts/svgNoLayer.py -d svg/core -s scripts/nolayeridcheck.txt
      - name: Check that SVGs and FZPs are ASCII or UTF-8
        run: python scripts/utf8stats.py . --verbose


  golang-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - name: Install fzp tool
        run: |
          go install github.com/fritzing/fzp/bin/fzp@latest
          fzp -v
          go install github.com/fritzing/fzb/bin/fzb@latest
          fzb -version
      - name: Fzp validate
        run: fzp validate --dir ./core
