name: check-all-parts
on: [push]
jobs:
  python-scripts:
    #runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - run: python scripts/checkascii.py .
      - run: python scripts/checkcase.py
      - run: python scripts/connectors_misnumbered.py -d .
      - run: python scripts/checkcopies.py -d svg

  golang-scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - name: Install fzp tool
        run: |
          go get github.com/fritzing/fzp/bin/fzp
          fzp -v
          go get github.com/fritzing/fzb/bin/fzb
          fzb -version
      - name: Fzp validate
        run: fzp validate --dir ./core
